name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run tests (Rust stable)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features

  docs:
    name: Check documentation (Rust stable)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo doc --all-features
        env:
          RUSTDOCFLAGS: "-D warnings"

  #test-miri:
  #  name: Run tests with miri (Rust nightly)
  #  runs-on: ubuntu-latest
  #
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: dtolnay/rust-toolchain@nightly
  #      with:
  #        components: miri
  #    - run: cargo miri test --all-features

  clippy:
    name: Run clippy (Rust nightly)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - run: cargo clippy --all-features -- -D warnings
